#!/usr/bin/env bash
set -euo pipefail

SOURCE_PROJECT="$HOME/Bioinformatics_Projects/variant-calling-workflow"

SOURCE_REFERENCE="$SOURCE_PROJECT/data/reference/ecoli_rel606.fasta"
SOURCE_R1="$SOURCE_PROJECT/data/reads/sample_R1.fastq"
SOURCE_R2="$SOURCE_PROJECT/data/reads/sample_R2.fastq"
SOURCE_VCF="$SOURCE_PROJECT/results/variants/sample.filtered.vcf"

REFERENCE_OUT="data/inputs/reference/ecoli_rel606_reference.fasta"
R1_OUT="data/inputs/reads/SRR2584866_R1_1000_reads.fastq"
R2_OUT="data/inputs/reads/SRR2584866_R2_1000_reads.fastq"
VCF_OUT="data/inputs/variants/SRR2584866_filtered_variants.vcf"

mkdir -p data/inputs/reference data/inputs/reads data/inputs/variants

for file in "$SOURCE_REFERENCE" "$SOURCE_R1" "$SOURCE_R2" "$SOURCE_VCF"; do
  if [ ! -f "$file" ]; then
    echo "Missing required source file: $file"
    echo "Make sure Project 4 has been run successfully first."
    exit 1
  fi
done

cp "$SOURCE_REFERENCE" "$REFERENCE_OUT"
cp "$SOURCE_VCF" "$VCF_OUT"

# FASTQ records are 4 lines each.
# 1,000 reads = 4,000 lines.
head -n 4000 "$SOURCE_R1" > "$R1_OUT"
head -n 4000 "$SOURCE_R2" > "$R2_OUT"

cat > data/inputs/README.md <<'DATAEOF'
# Input data

This folder contains real bioinformatics input files used to demonstrate the utility scripts.

## Files

| File | Description |
|---|---|
| `reference/ecoli_rel606_reference.fasta` | E. coli REL606 reference genome copied from the variant-calling workflow project |
| `reads/SRR2584866_R1_1000_reads.fastq` | First 1,000 reads from a real paired-end E. coli FASTQ file |
| `reads/SRR2584866_R2_1000_reads.fastq` | First 1,000 reads from the matching read 2 FASTQ file |
| `variants/SRR2584866_filtered_variants.vcf` | Filtered VCF generated by the variant-calling workflow project |

The FASTQ files are subsetted so the repository remains lightweight while still using real sequencing reads.
DATAEOF

echo "Input data prepared:"
ls -lh data/inputs/reference
ls -lh data/inputs/reads
ls -lh data/inputs/variants
